name: code-to-gitbooks

on:
  schedule:
    - cron: "0 0 * * *" #runs at 00:00 UTC everyday
      
jobs:
  code-to-gitbooks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
      
    - name: Execute py script to copy python file to CODE.md
      run: |
        python scripts/run.py

    - name: Commit CODE.md
      uses: stefanzweifel/git-auto-commit-action@v4.14.1
      with:
        commit_message: Sync python code to CODE.md

